name: db
channels:
- https://conda.anaconda.org/conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- arrow-cpp=11.0.0
- aws-c-auth=0.6.23
- aws-c-cal=0.5.20
- aws-c-common=0.8.9
- aws-c-compression=0.2.16
- aws-c-event-stream=0.2.18
- aws-c-http=0.7.3
- aws-c-io=0.13.14
- aws-c-mqtt=0.8.6
- aws-c-s3=0.2.3
- aws-c-sdkutils=0.1.7
- aws-checksums=0.1.14
- aws-crt-cpp=0.18.16
- aws-sdk-cpp=1.10.57
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2022.12.7
- certifi=2022.12.7
- cffi=1.15.1
- charset-normalizer=2.1.1
- click=8.1.3
- colorama=0.4.6
- cryptography=39.0.0
- cudatoolkit=11.8.0
- dnspython=2.3.0
- et_xmlfile=1.1.0
- fastcore=1.5.26
- fastprogress=1.0.3
- geographiclib=1.52
- geopy=2.3.0
- gflags=2.2.2
- glog=0.6.0
- idna=3.4
- keyutils=1.6.1
- krb5=1.20.1
- ld_impl_linux-64=2.39
- libabseil=20220623.0
- libarrow=11.0.0
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libcrc32c=1.1.2
- libcurl=7.87.0
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.10
- libffi=3.4.2
- libgcc-ng=12.2.0
- libgfortran-ng=12.2.0
- libgfortran5=12.2.0
- libgomp=12.2.0
- libgoogle-cloud=2.7.0
- libgrpc=1.51.1
- libiconv=1.17
- liblapack=3.9.0
- libnghttp2=1.51.0
- libnsl=2.0.0
- libopenblas=0.3.21
- libprotobuf=3.21.12
- libsqlite=3.40.0
- libssh2=1.10.0
- libstdcxx-ng=12.2.0
- libthrift=0.16.0
- libutf8proc=2.8.0
- libuuid=2.32.1
- libzlib=1.2.13
- lz4-c=1.9.4
- markdown-it-py=2.1.0
- mdurl=0.1.0
- ncurses=6.3
- numpy=1.24.2
- openpyxl=3.1.0
- openssl=3.0.7
- orc=1.8.2
- packaging=23.0
- pandas=1.5.3
- parquet-cpp=1.5.1
- pip=22.3.1
- pyarrow=11.0.0
- pycparser=2.21
- pygments=2.14.0
- pymongo=4.3.3
- pyodbc=4.0.35
- pyopenssl=23.0.0
- pysocks=1.7.1
- python=3.10.8
- python-dateutil=2.8.2
- python-dotenv=0.21.1
- python_abi=3.10
- pytz=2022.7.1
- re2=2023.02.01
- readline=8.1.2
- requests=2.28.2
- rich=13.3.1
- s2n=1.3.35
- setuptools=65.6.3
- six=1.16.0
- snappy=1.1.9
- tk=8.6.12
- tqdm=4.64.1
- typing_extensions=4.4.0
- tzdata=2022g
- ucx=1.12.1
- unixodbc=2.3.10
- urllib3=1.26.14
- wheel=0.38.4
- xmltodict=0.13.0
- xz=5.2.6
- zlib=1.2.13
- zstd=1.5.2

